FROM openjdk:17-jdk-slim as Build
WORKDIR /planing-todo
COPY . .
RUN ./mvnw -DskipTests clean package

FROM openjdk:17-jdk-slim
ARG JAR_FILE=target/*.jar
COPY --from=build /planing-todo/target/planing-todo-0.0.1.jar app.jar
ENTRYPOINT ["java","-jar","/app.jar"]


